import { useEffect, useRef, useState } from "react";
import { ActivityIndicator, BackHandler, StyleSheet, Text, View } from "react-native";
import { Check, Circle } from "lucide-react-native";
import { router, useLocalSearchParams } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { VideoCard } from "@/components/VideoCard";
import { analyzeServe, type ProcessingStage } from "@/services/analyzer";
import { colors, radius, spacing } from "@/constants/theme";
import type { ServeMetadata } from "@/types/analysis";
const stages:[ProcessingStage,string][]=[["uploading","Uploading video"],["detecting","Detecting serve"],["tracking","Tracking body and racket"],["scoring","Scoring mechanics"],["feedback","Generating feedback"]];
export default function ProcessingScreen(){const params=useLocalSearchParams<{uri:string;cameraAngle:ServeMetadata["cameraAngle"];dominantHand:ServeMetadata["dominantHand"];serveType:ServeMetadata["serveType"]}>();const [stage,setStage]=useState<ProcessingStage>("uploading");const [percent,setPercent]=useState(0);const submitted=useRef(false);
  useEffect(()=>{const subscription=BackHandler.addEventListener("hardwareBackPress",()=>true);if(!submitted.current&&params.uri){submitted.current=true;analyzeServe(params.uri,{cameraAngle:params.cameraAngle??"Side",dominantHand:params.dominantHand??"Right",serveType:params.serveType??"Flat"},update=>{setStage(update.stage);setPercent(update.percent)}).then(()=>router.replace({pathname:"/results",params:{uri:params.uri}}))}return()=>subscription.remove()},[params.cameraAngle,params.dominantHand,params.serveType,params.uri]);
  const active=stages.findIndex(([id])=>id===stage);return <SafeAreaView style={styles.safe}><View style={styles.content}><Text style={styles.kicker}>ANALYSIS IN PROGRESS</Text><Text style={styles.title}>Reading your motion</Text><Text style={styles.intro}>Keep ServeTech open while we analyze each phase of your serve.</Text><VideoCard uri={params.uri} compact/><View style={styles.progress}><View style={[styles.progressFill,{width:`${percent}%`}]} /></View><View style={styles.percentRow}><Text style={styles.current}>{stages[Math.max(active,0)]?.[1]??"Finishing analysis"}</Text><Text style={styles.percent}>{percent}%</Text></View><View style={styles.stages}>{stages.map(([id,label],index)=>{const done=active>index||stage==="complete";const current=active===index;return <View key={id} style={styles.stage}>{done?<View style={styles.done}><Check size={15} color={colors.text}/></View>:current?<View style={styles.active}><ActivityIndicator size="small" color={colors.text}/></View>:<Circle size={22} color={colors.border}/>}<Text style={[styles.stageText,!done&&!current&&styles.pending]}>{label}</Text></View>})}</View><Text style={styles.note}>This mock analysis runs entirely on your device. A real analyzer API will replace it later.</Text></View></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{flex:1,paddingHorizontal:spacing.xl,paddingTop:spacing.xl},kicker:{fontSize:11,fontWeight:"900",letterSpacing:1.6,color:colors.muted},title:{fontSize:30,fontWeight:"900",letterSpacing:-1,color:colors.text,marginTop:4},intro:{fontSize:14,lineHeight:21,color:colors.muted,marginTop:spacing.sm,marginBottom:spacing.xl},progress:{height:7,borderRadius:4,backgroundColor:colors.border,overflow:"hidden",marginTop:spacing.xl},progressFill:{height:7,borderRadius:4,backgroundColor:colors.primary},percentRow:{flexDirection:"row",justifyContent:"space-between",marginTop:spacing.sm},current:{fontSize:13,fontWeight:"800",color:colors.text},percent:{fontSize:13,fontWeight:"900",color:colors.text},stages:{marginTop:spacing.xl,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,gap:spacing.lg},stage:{flexDirection:"row",alignItems:"center",gap:spacing.md},done:{width:24,height:24,borderRadius:12,backgroundColor:colors.primary,alignItems:"center",justifyContent:"center"},active:{width:24,height:24,borderRadius:12,backgroundColor:colors.surface,alignItems:"center",justifyContent:"center"},stageText:{fontSize:14,fontWeight:"800",color:colors.text},pending:{color:colors.muted,fontWeight:"600"},note:{fontSize:10,lineHeight:15,color:colors.muted,textAlign:"center",marginTop:"auto",marginBottom:spacing.xl}});

