import { Pressable, StyleSheet, Text, View } from "react-native";
import { Pause, Play, RotateCcw, Trash2 } from "lucide-react-native";
import { useVideoPlayer, VideoView } from "expo-video";
import { colors, radius, spacing } from "@/constants/theme";
export function VideoCard({uri,onRemove,compact=false}:{uri?:string;onRemove?:()=>void;compact?:boolean}){return uri?<NativeVideo uri={uri} onRemove={onRemove} compact={compact}/>:<View style={[styles.placeholder,compact&&styles.compact]}><View style={styles.courtLine}/><View style={styles.play}><Play size={24} fill={colors.text} color={colors.text}/></View><Text style={styles.frame}>TROPHY POSITION · FRAME 42</Text></View>}
function NativeVideo({uri,onRemove,compact}:{uri:string;onRemove?:()=>void;compact:boolean}){const player=useVideoPlayer(uri,p=>{p.loop=true});return <View style={[styles.wrap,compact&&styles.compact]}><VideoView player={player} style={StyleSheet.absoluteFill} nativeControls={!compact} contentFit="contain"/>{onRemove&&<Pressable accessibilityLabel="Remove video" onPress={onRemove} style={styles.remove}><Trash2 size={18} color={colors.white}/></Pressable>}</View>}
export function FrameControls(){return <View style={styles.controls}><Pressable style={styles.control} accessibilityLabel="Previous frame"><RotateCcw size={18} color={colors.text}/></Pressable><Pressable style={styles.pause} accessibilityLabel="Play or pause"><Pause size={18} color={colors.text}/></Pressable><View style={styles.timeline}><View style={styles.elapsed}/><View style={styles.knob}/></View><Text style={styles.time}>00:01.40</Text></View>}
const styles=StyleSheet.create({wrap:{height:240,borderRadius:radius.lg,overflow:"hidden",backgroundColor:"#172117"},placeholder:{height:240,borderRadius:radius.lg,overflow:"hidden",backgroundColor:"#263326",alignItems:"center",justifyContent:"center"},compact:{height:190},courtLine:{position:"absolute",width:1,height:"120%",backgroundColor:"rgba(255,255,255,.24)",transform:[{rotate:"-8deg"}]},play:{width:58,height:58,borderRadius:29,backgroundColor:colors.primary,alignItems:"center",justifyContent:"center"},frame:{position:"absolute",bottom:spacing.md,left:spacing.md,color:colors.white,fontSize:10,fontWeight:"800",letterSpacing:.6,backgroundColor:"rgba(0,0,0,.45)",padding:spacing.sm,borderRadius:radius.pill},remove:{position:"absolute",right:spacing.md,top:spacing.md,width:42,height:42,borderRadius:21,alignItems:"center",justifyContent:"center",backgroundColor:"rgba(0,0,0,.62)"},controls:{height:54,flexDirection:"row",alignItems:"center",gap:spacing.sm},control:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:colors.border,alignItems:"center",justifyContent:"center"},pause:{width:42,height:42,borderRadius:21,backgroundColor:colors.primary,alignItems:"center",justifyContent:"center"},timeline:{height:4,backgroundColor:colors.border,borderRadius:2,flex:1},elapsed:{width:"38%",height:4,backgroundColor:colors.primary},knob:{position:"absolute",left:"36%",top:-4,width:12,height:12,borderRadius:6,backgroundColor:colors.text},time:{fontSize:11,color:colors.muted,fontWeight:"700"}});

