import { Tabs } from "expo-router";
import { Platform, Pressable, StyleSheet, Text, View } from "react-native";
import { Plus, Settings, UserRound } from "lucide-react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { colors } from "@/constants/theme";
export default function TabLayout(){const insets=useSafeAreaInsets();return <Tabs screenOptions={{headerShown:false,tabBarShowLabel:false,tabBarStyle:[styles.bar,{height:72+insets.bottom,paddingBottom:insets.bottom}],tabBarActiveTintColor:colors.text,tabBarInactiveTintColor:colors.muted}}>
  <Tabs.Screen name="index" options={{title:"Profile",tabBarAccessibilityLabel:"Profile",tabBarIcon:({color,focused})=><TabIcon label="Profile" focused={focused}><UserRound color={color} size={23} strokeWidth={focused?2.6:2}/></TabIcon>}}/>
  <Tabs.Screen name="add" options={{title:"Add Serve",tabBarAccessibilityLabel:"Add Serve",tabBarButton:({onPress,onLongPress,accessibilityState})=><Pressable onPress={onPress} onLongPress={onLongPress} accessibilityState={accessibilityState} accessibilityRole="button" accessibilityLabel="Add Serve" style={({pressed})=>[styles.addWrap,pressed&&styles.pressed]}><View style={styles.addButton}><Plus size={31} color={colors.text} strokeWidth={2.6}/></View><Text style={styles.addLabel}>Add Serve</Text></Pressable>}}/>
  <Tabs.Screen name="settings" options={{title:"Settings",tabBarAccessibilityLabel:"Settings",tabBarIcon:({color,focused})=><TabIcon label="Settings" focused={focused}><Settings color={color} size={23} strokeWidth={focused?2.6:2}/></TabIcon>}}/>
  </Tabs>}
function TabIcon({label,focused,children}:{label:string;focused:boolean;children:React.ReactNode}){return <View style={styles.tab}><View style={[styles.indicator,focused&&styles.indicatorActive]}/>{children}<Text style={[styles.label,focused&&styles.labelActive]}>{label}</Text></View>}
const styles=StyleSheet.create({bar:{position:"absolute",borderTopWidth:1,borderTopColor:colors.border,backgroundColor:colors.white,elevation:0,shadowOpacity:0,paddingTop:8},tab:{alignItems:"center",gap:3,minWidth:80},indicator:{height:3,width:18,borderRadius:2,backgroundColor:"transparent",marginBottom:2},indicatorActive:{backgroundColor:colors.primary},label:{fontSize:11,fontWeight:"700",color:colors.muted},labelActive:{color:colors.text},addWrap:{top:-24,alignItems:"center",justifyContent:"center",flex:1},addButton:{width:64,height:64,borderRadius:32,backgroundColor:colors.primary,alignItems:"center",justifyContent:"center",borderWidth:5,borderColor:colors.white,...Platform.select({ios:{shadowColor:colors.text,shadowOpacity:.12,shadowRadius:10,shadowOffset:{width:0,height:5}},android:{elevation:5}})},addLabel:{fontSize:11,fontWeight:"800",color:colors.text,marginTop:2},pressed:{transform:[{scale:.94}]}});
