import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import * as ImagePicker from "expo-image-picker";
import { Camera, Image as ImageIcon, Info, RotateCcw, Trash2 } from "lucide-react-native";
import { router } from "expo-router";
import { Screen } from "@/components/Screen";
import { AppButton } from "@/components/AppButton";
import { VideoCard } from "@/components/VideoCard";
import { colors, radius, spacing } from "@/constants/theme";
import type { SelectedVideo, ServeMetadata } from "@/types/analysis";
const selectors={dominantHand:["Right","Left"],serveType:["Flat","Kick","Slice"]} as const;
export default function AddServeScreen(){const [video,setVideo]=useState<SelectedVideo|null>(null);const [error,setError]=useState("");const [metadata,setMetadata]=useState<ServeMetadata>({dominantHand:"Right",serveType:"Flat"});
  async function pick(source:"camera"|"library"){setError("");try{const permission=source==="camera"?await ImagePicker.requestCameraPermissionsAsync():await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){setError(`Camera${source==="library"?" roll":""} permission is required to add a serve video.`);return}const result=source==="camera"?await ImagePicker.launchCameraAsync({mediaTypes:["videos"],videoMaxDuration:30,quality:1}):await ImagePicker.launchImageLibraryAsync({mediaTypes:["videos"],allowsEditing:false});if(!result.canceled){const asset=result.assets[0];setVideo({uri:asset.uri,fileName:asset.fileName??"serve-video.mov",fileSize:asset.fileSize,duration:asset.duration??undefined})}}catch{setError("We couldn’t open your camera or library. Please try again.")}}
  function next(){if(!video){setError("Record or choose a video before analyzing your serve.");return}router.push({pathname:"/trim",params:{uri:video.uri,dominantHand:metadata.dominantHand,serveType:metadata.serveType}})}
  return <Screen contentContainerStyle={styles.screen}><Text style={styles.kicker}>NEW ANALYSIS</Text><Text style={styles.title}>Add your serve</Text><Text style={styles.intro}>A short, steady clip is all Serve Goat needs to evaluate your motion.</Text>
    {video?<><VideoCard uri={video.uri} onRemove={()=>setVideo(null)}/><View style={styles.file}><View style={{flex:1}}><Text numberOfLines={1} style={styles.fileName}>{video.fileName}</Text><Text style={styles.fileMeta}>{video.fileSize?`${(video.fileSize/1048576).toFixed(1)} MB`:"Video selected"}{video.duration?` · ${Math.round(video.duration/1000)} sec`:""}</Text></View><Pressable accessibilityLabel="Replace video" onPress={()=>pick("library")} style={styles.iconButton}><RotateCcw size={18} color={colors.text}/></Pressable><Pressable accessibilityLabel="Remove video" onPress={()=>setVideo(null)} style={styles.iconButton}><Trash2 size={18} color={colors.error}/></Pressable></View></>:<View style={styles.sources}><Pressable onPress={()=>pick("camera")} style={({pressed})=>[styles.source,pressed&&styles.pressed]}><View style={styles.sourceIcon}><Camera size={26} color={colors.text}/></View><Text style={styles.sourceTitle}>Record a video</Text><Text style={styles.sourceText}>Open the camera</Text></Pressable><Pressable onPress={()=>pick("library")} style={({pressed})=>[styles.source,pressed&&styles.pressed]}><View style={styles.sourceIcon}><ImageIcon size={26} color={colors.text}/></View><Text style={styles.sourceTitle}>Photo library</Text><Text style={styles.sourceText}>Choose an existing clip</Text></Pressable></View>}
    <View style={styles.tip}><Info size={20} color={colors.text}/><View style={{flex:1}}><Text style={styles.tipTitle}>For the best analysis</Text><Text style={styles.tipText}>Film your full body and racket. Keep the phone still, landscape, and about 15 feet away.</Text></View></View>
    <Selector label="Dominant hand" values={selectors.dominantHand} selected={metadata.dominantHand} onSelect={value=>setMetadata({...metadata,dominantHand:value})}/><Selector label="Serve type" values={selectors.serveType} selected={metadata.serveType} onSelect={value=>setMetadata({...metadata,serveType:value})}/>
    {!!error&&<Text accessibilityRole="alert" style={styles.error}>{error}</Text>}<AppButton label="Continue" onPress={next} disabled={!video}/></Screen>}
function Selector<T extends string>({label,values,selected,onSelect}:{label:string;values:readonly T[];selected:T;onSelect:(value:T)=>void}){return <View style={styles.selector}><Text style={styles.selectorLabel}>{label}</Text><View style={styles.options}>{values.map(value=><Pressable key={value} onPress={()=>onSelect(value)} style={[styles.option,selected===value&&styles.optionActive]}><Text style={[styles.optionText,selected===value&&styles.optionTextActive]}>{value}</Text></Pressable>)}</View></View>}
const styles=StyleSheet.create({screen:{paddingBottom:130},kicker:{fontSize:11,fontWeight:"900",letterSpacing:1.7,color:colors.muted},title:{fontSize:32,fontWeight:"900",color:colors.text,letterSpacing:-1,marginTop:4},intro:{fontSize:15,lineHeight:23,color:colors.muted,marginTop:spacing.sm,marginBottom:spacing.xl},sources:{flexDirection:"row",gap:spacing.md},source:{flex:1,minHeight:154,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,justifyContent:"center"},pressed:{transform:[{scale:.98}],backgroundColor:colors.surface},sourceIcon:{width:48,height:48,borderRadius:24,backgroundColor:colors.primary,alignItems:"center",justifyContent:"center",marginBottom:spacing.md},sourceTitle:{fontSize:15,fontWeight:"800",color:colors.text},sourceText:{fontSize:12,color:colors.muted,marginTop:4},tip:{flexDirection:"row",gap:spacing.md,backgroundColor:colors.surface,borderRadius:radius.md,padding:spacing.lg,marginVertical:spacing.xl},tipTitle:{fontSize:14,fontWeight:"800",color:colors.text},tipText:{fontSize:12,lineHeight:18,color:colors.muted,marginTop:3},file:{flexDirection:"row",alignItems:"center",gap:spacing.sm,paddingVertical:spacing.md,marginBottom:spacing.sm},fileName:{fontSize:14,fontWeight:"800",color:colors.text},fileMeta:{fontSize:12,color:colors.muted,marginTop:3},iconButton:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:colors.border,alignItems:"center",justifyContent:"center"},selector:{marginBottom:spacing.xl},selectorLabel:{fontSize:13,fontWeight:"800",color:colors.text,marginBottom:spacing.sm},options:{flexDirection:"row",gap:spacing.sm},option:{minHeight:44,flex:1,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:colors.border,borderRadius:radius.pill},optionActive:{backgroundColor:colors.surface,borderColor:colors.primary},optionText:{fontSize:13,fontWeight:"700",color:colors.muted},optionTextActive:{color:colors.text},error:{fontSize:13,lineHeight:19,color:colors.error,backgroundColor:"#FFF2F2",padding:spacing.md,borderRadius:radius.md,marginBottom:spacing.md}});
