import { useCallback, useState } from "react";
import { Pressable, StyleSheet, Switch, Text, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { Bell, ChevronRight, CircleHelp, Crown, Database, Info, LogOut, Ruler, Shield, UserRound } from "lucide-react-native";
import { Screen } from "@/components/Screen";
import { colors, radius, spacing } from "@/constants/theme";
import { FREE_SERVE_LIMIT, getPurchaseState } from "@/services/purchaseStore";
import { isUnlocked } from "@/services/purchases";
import { getProfile } from "@/services/userStore";
import type { UserProfile } from "@/types/user";
function rows(profile:UserProfile|null,unlocked:boolean,freeRemaining:number|null){return [{icon:UserRound,label:"Account",value:profile?`${profile.firstName} ${profile.lastName}`.trim():"—",onPress:()=>router.push("/account")},{icon:Crown,label:"Upgrade",value:unlocked?"Unlimited":freeRemaining===null?"—":`${freeRemaining} free serve${freeRemaining===1?"":"s"} left`,onPress:()=>router.push("/paywall")},{icon:Shield,label:"Video privacy",value:"Private"},{icon:Database,label:"Data usage",value:"Wi-Fi only"},{icon:Ruler,label:"Units",value:"Imperial"},{icon:CircleHelp,label:"Help & feedback"},{icon:Info,label:"About",value:"Version 1.0"}]}
export default function SettingsScreen(){const [profile,setProfile]=useState<UserProfile|null>(null);const [unlocked,setUnlocked]=useState(false);const [freeRemaining,setFreeRemaining]=useState<number|null>(null);useFocusEffect(useCallback(()=>{getProfile().then(setProfile);isUnlocked().then(setUnlocked);getPurchaseState().then(state=>setFreeRemaining(Math.max(0,FREE_SERVE_LIMIT-state.freeServesUsed)))},[]));const list=rows(profile,unlocked,freeRemaining);
  return <Screen contentContainerStyle={styles.screen}><Text style={styles.kicker}>PREFERENCES</Text><Text style={styles.title}>Settings</Text><Text style={styles.section}>GENERAL</Text><View style={styles.card}><View style={styles.row}><View style={styles.icon}><Bell size={20} color={colors.text}/></View><View style={{flex:1}}><Text style={styles.label}>Notifications</Text><Text style={styles.value}>Analysis updates and reminders</Text></View><Switch value trackColor={{false:colors.border,true:colors.primary}} thumbColor={colors.white}/></View>{list.slice(0,5).map(Row)}</View><Text style={styles.section}>SUPPORT</Text><View style={styles.card}>{list.slice(5).map(Row)}</View><Pressable style={styles.signOut} accessibilityRole="button"><LogOut size={20} color={colors.error}/><Text style={styles.signOutText}>Sign out</Text><Text style={styles.placeholder}>Placeholder</Text></Pressable><Text style={styles.legal}>Serve Goat protects your videos and uses them only according to your privacy preferences.</Text></Screen>}
function Row({icon:Icon,label,value,onPress}:{icon:typeof UserRound;label:string;value?:string;onPress?:()=>void}){return <Pressable key={label} onPress={onPress} style={({pressed})=>[styles.row,pressed&&{backgroundColor:colors.soft}]}><View style={styles.icon}><Icon size={20} color={colors.text}/></View><View style={{flex:1}}><Text style={styles.label}>{label}</Text>{value&&<Text style={styles.value}>{value}</Text>}</View><ChevronRight size={19} color={colors.muted}/></Pressable>}
const styles=StyleSheet.create({screen:{paddingBottom:120},kicker:{fontSize:11,fontWeight:"900",letterSpacing:1.7,color:colors.muted},title:{fontSize:32,fontWeight:"900",color:colors.text,letterSpacing:-1,marginTop:4,marginBottom:spacing.xxl},section:{fontSize:10,fontWeight:"900",letterSpacing:1.5,color:colors.muted,marginBottom:spacing.sm,marginLeft:4},card:{borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,overflow:"hidden",marginBottom:spacing.xl},row:{minHeight:72,flexDirection:"row",alignItems:"center",gap:spacing.md,paddingHorizontal:spacing.lg,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.border},icon:{width:40,height:40,borderRadius:20,backgroundColor:colors.surface,alignItems:"center",justifyContent:"center"},label:{fontSize:15,fontWeight:"800",color:colors.text},value:{fontSize:12,color:colors.muted,marginTop:3},signOut:{height:58,borderWidth:1,borderColor:"#F2CACA",borderRadius:radius.md,flexDirection:"row",alignItems:"center",gap:spacing.md,paddingHorizontal:spacing.lg},signOutText:{fontSize:15,fontWeight:"800",color:colors.error,flex:1},placeholder:{fontSize:10,fontWeight:"700",color:colors.muted},legal:{fontSize:11,lineHeight:17,textAlign:"center",color:colors.muted,margin:spacing.xl}});
